# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: White Rabbits
author: grab0id
email: ""
description: >+ # this means to ignore newlines until "baseurl:"
  Here lie my exploits and adventures into the world of offensive
  security. I'm not here to pretend I know anything; I'm just here 
  to learn and grow...and maybe be a penetration tester one day. glhf!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grab0id.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Social info
twitter_username: djbrooks311
github_username:  grab0id
linkedin_username:  danieljbrooks

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
